### PR TITLE
fix(common): Fix repository name validation

### LINKED ISSUE #1488: Underscore in repository breaks indexing
**Describe the bug**
This entry breaks indexing.
```
[[repositories]]
name = "slide_tracker"
git_url = "/code/hobby/slide_tracker"
```
```
  Parsing config failed

  Warning: Could not parse the Tabby configuration at /data/config.toml
  Reason: Invalid characters in repository name: slide_tracker
  Falling back to default config, please resolve the errors and restart Tabby
```

I see this was changed [here](https://github.com/TabbyML/tabby/blob/8a38e2bde49217ce693d54995eb299cfae733b71/crates/tabby-common/src/config.rs#L70)

**Information about your version**
tabbyml/tabby:nightly
tabby 0.9.0-dev

**Information about your GPU**
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:04:00.0 Off |                  Off |
| N/A   52C    P0    54W / 250W |  20654MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:09:00.0  On |                  N/A |
|  0%   50C    P5    20W / 125W |    685MiB /  6144MiB |     14%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

### PR DESCRIPTION
**Pull request by boxbeam**
Fixes #1488

### CODE REVIEW

File: crates/tabby-common/src/config.rs [hunk 1]
```diff
@@ -67,7 +67,7 @@ impl Config {
 }
 
 lazy_static! {
-    pub static ref REPOSITORY_NAME_REGEX: Regex = Regex::new("^[a-zA-Z][a-zA-Z0-9-]+$").unwrap();
+    pub static ref REPOSITORY_NAME_REGEX: Regex = Regex::new("^[a-zA-Z][\\w.-]+$").unwrap();
```
Comment (wsxiaoys) [inline crates/tabby-common/src/config.rs:70]: add a unit test to cover the regression

Comment (boxbeam) [reply crates/tabby-common/src/config.rs:70]: already did
