### PR TITLE
fix(webserver): support http protocol for gitlab

### LINKED ISSUE #2500: Add support for http Self Hosted Repository Providers addresses
I would like to request the support for self-hosted repository providers with HTTP addresses. Currently, TabbyML only supports HTTPS addresses which restricts its usability with our repositories. 

Thanks !

### PR DESCRIPTION
**Pull request by wsxiaoys**
fix #2500

### CODE REVIEW

File: ee/tabby-webserver/src/service/mod.rs [hunk 1]
```diff
@@ -311,9 +311,11 @@ pub async fn create_gitlab_client(
     // Gitlab client expects a url base like "gitlab.com" not "https://gitlab.com"
     // We still want to take a more consistent format as user input, so this
     // will help normalize it to prevent confusion
```
Comment (boxbeam) [inline ee/tabby-webserver/src/service/mod.rs:313]:
```suggestion
```

Since it seems the new version of `gitlab` no longer has this quirk, we should remove this comment

**Review by boxbeam — APPROVED** [review]
Otherwise LGTM (tested it locally to ensure this works)

File: ee/tabby-webserver/src/service/mod.rs (hunk 1 above)
Comment (wsxiaoys) [reply ee/tabby-webserver/src/service/mod.rs:313]: Does it mean we can pass in "https://..." or "http://..." directly, without having to set `insecure` by ourselves?

Comment (boxbeam) [reply ee/tabby-webserver/src/service/mod.rs:313]: Potentially, but I think it's still a good idea for correctness

Comment (boxbeam) [reply ee/tabby-webserver/src/service/mod.rs:313]: https://docs.rs/gitlab/latest/src/gitlab/gitlab.rs.html#417-502 Seems it will change it to https unless insecure is set

Comment (wsxiaoys) [reply ee/tabby-webserver/src/service/mod.rs:313]: ok - then will keep the current implementation
